name=DomovoyClient
version=1.0.0
author=Domovoy
maintainer=Domovoy
sentence=Client library for Domovoy Home Automation System
paragraph=Provides device discovery and command handling for Domovoy Native Protocol.
category=Communication
url=https://github.com/drakus/domovoy
architectures=*
depends=PubSubClient,ArduinoJson
